# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efdb559e48912ae18f76ab49181a7f0421ce8f87f7bd7aaa4d9e25ef4cd50c4346164c0a46364f1db8d6154f5a325054b46a651fbab45bbe0b0caa6e6d8c4982

test:
  secret_key_base: 840214efaeb93147593c7c178d591cbdd59bfa182a47bf29c52b49fc820c6b743e3ee9c8479cead4a9e1e12c2f2d434c8e7546698e48936278ee16c8e599cc87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
